package com.md.sensorsactivity;

import android.util.Log;

import java.util.ArrayList;

import weka.core.Attribute;
import weka.core.DenseInstance;
import weka.core.Instance;
import weka.core.Instances;

public class Classification {

    public double runClassification(double[] dataArray) {

        double result = -1;
        Instance inst_co;

        try {

            //Create list of attributes
            ArrayList<Attribute> attributeList = new ArrayList<Attribute>(128);

            //Set attributes
            Attribute data1 = new Attribute("data1");
            Attribute data2 = new Attribute("data2");
            Attribute data3 = new Attribute("data3");
            Attribute data4 = new Attribute("data4");
            Attribute data5 = new Attribute("data5");
            Attribute data6 = new Attribute("data6");
            Attribute data7 = new Attribute("data7");
            Attribute data8 = new Attribute("data8");
            Attribute data9 = new Attribute("data9");
            Attribute data10 = new Attribute("data10");
            Attribute data11 = new Attribute("data11");
            Attribute data12 = new Attribute("data12");
            Attribute data13 = new Attribute("data13");
            Attribute data14 = new Attribute("data14");
            Attribute data15 = new Attribute("data15");
            Attribute data16 = new Attribute("data16");
            Attribute data17 = new Attribute("data17");
            Attribute data18 = new Attribute("data18");
            Attribute data19 = new Attribute("data19");
            Attribute data20 = new Attribute("data20");
            Attribute data21 = new Attribute("data21");
            Attribute data22 = new Attribute("data22");
            Attribute data23 = new Attribute("data23");
            Attribute data24 = new Attribute("data24");
            Attribute data25 = new Attribute("data25");
            Attribute data26 = new Attribute("data26");
            Attribute data27 = new Attribute("data27");
            Attribute data28 = new Attribute("data28");
            Attribute data29 = new Attribute("data29");
            Attribute data30 = new Attribute("data30");
            Attribute data31 = new Attribute("data31");
            Attribute data32 = new Attribute("data32");
            Attribute data33 = new Attribute("data33");
            Attribute data34 = new Attribute("data34");
            Attribute data35 = new Attribute("data35");
            Attribute data36 = new Attribute("data36");
            Attribute data37 = new Attribute("data37");
            Attribute data38 = new Attribute("data38");
            Attribute data39 = new Attribute("data39");
            Attribute data40 = new Attribute("data40");
            Attribute data41 = new Attribute("data41");
            Attribute data42 = new Attribute("data42");
            Attribute data43 = new Attribute("data43");
            Attribute data44 = new Attribute("data44");
            Attribute data45 = new Attribute("data45");
            Attribute data46 = new Attribute("data46");
            Attribute data47 = new Attribute("data47");
            Attribute data48 = new Attribute("data48");
            Attribute data49 = new Attribute("data49");
            Attribute data50 = new Attribute("data50");
            Attribute data51 = new Attribute("data51");
            Attribute data52 = new Attribute("data52");
            Attribute data53 = new Attribute("data53");
            Attribute data54 = new Attribute("data54");
            Attribute data55 = new Attribute("data55");
            Attribute data56 = new Attribute("data56");
            Attribute data57 = new Attribute("data57");
            Attribute data58 = new Attribute("data58");
            Attribute data59 = new Attribute("data59");
            Attribute data60 = new Attribute("data60");
            Attribute data61 = new Attribute("data61");
            Attribute data62 = new Attribute("data62");
            Attribute data63 = new Attribute("data63");
            Attribute data64 = new Attribute("data64");
            Attribute data65 = new Attribute("data65");
            Attribute data66 = new Attribute("data66");
            Attribute data67 = new Attribute("data67");
            Attribute data68 = new Attribute("data68");
            Attribute data69 = new Attribute("data69");
            Attribute data70 = new Attribute("data70");
            Attribute data71 = new Attribute("data71");
            Attribute data72 = new Attribute("data72");
            Attribute data73 = new Attribute("data73");
            Attribute data74 = new Attribute("data74");
            Attribute data75 = new Attribute("data75");
            Attribute data76 = new Attribute("data76");
            Attribute data77 = new Attribute("data77");
            Attribute data78 = new Attribute("data78");
            Attribute data79 = new Attribute("data79");
            Attribute data80 = new Attribute("data80");
            Attribute data81 = new Attribute("data81");
            Attribute data82 = new Attribute("data82");
            Attribute data83 = new Attribute("data83");
            Attribute data84 = new Attribute("data84");
            Attribute data85 = new Attribute("data85");
            Attribute data86 = new Attribute("data86");
            Attribute data87 = new Attribute("data87");
            Attribute data88 = new Attribute("data88");
            Attribute data89 = new Attribute("data89");
            Attribute data90 = new Attribute("data90");
            Attribute data91 = new Attribute("data91");
            Attribute data92 = new Attribute("data92");
            Attribute data93 = new Attribute("data93");
            Attribute data94 = new Attribute("data94");
            Attribute data95 = new Attribute("data95");
            Attribute data96 = new Attribute("data96");
            Attribute data97 = new Attribute("data97");
            Attribute data98 = new Attribute("data98");
            Attribute data99 = new Attribute("data99");
            Attribute data100 = new Attribute("data100");
            Attribute data101 = new Attribute("data101");
            Attribute data102 = new Attribute("data102");
            Attribute data103 = new Attribute("data103");
            Attribute data104 = new Attribute("data104");
            Attribute data105 = new Attribute("data105");
            Attribute data106 = new Attribute("data106");
            Attribute data107 = new Attribute("data107");
            Attribute data108 = new Attribute("data108");
            Attribute data109 = new Attribute("data109");
            Attribute data110 = new Attribute("data110");
            Attribute data111 = new Attribute("data111");
            Attribute data112 = new Attribute("data112");
            Attribute data113 = new Attribute("data113");
            Attribute data114 = new Attribute("data114");
            Attribute data115 = new Attribute("data115");
            Attribute data116 = new Attribute("data116");
            Attribute data117 = new Attribute("data117");
            Attribute data118 = new Attribute("data118");
            Attribute data119 = new Attribute("data119");
            Attribute data120 = new Attribute("data120");
            Attribute data121 = new Attribute("data121");
            Attribute data122 = new Attribute("data122");
            Attribute data123 = new Attribute("data123");
            Attribute data124 = new Attribute("data124");
            Attribute data125 = new Attribute("data125");
            Attribute data126 = new Attribute("data126");
            Attribute data127 = new Attribute("data127");
            Attribute data128 = new Attribute("data128");

            //Class attribute
            ArrayList<String> classVal = new ArrayList<String>();
            classVal.add("chodzenie");
            classVal.add("stanie");

            //Add attributes to list
            attributeList.add(data1);
            attributeList.add(data2);
            attributeList.add(data3);
            attributeList.add(data4);
            attributeList.add(data5);
            attributeList.add(data6);
            attributeList.add(data7);
            attributeList.add(data8);
            attributeList.add(data9);
            attributeList.add(data10);
            attributeList.add(data11);
            attributeList.add(data12);
            attributeList.add(data13);
            attributeList.add(data14);
            attributeList.add(data15);
            attributeList.add(data16);
            attributeList.add(data17);
            attributeList.add(data18);
            attributeList.add(data19);
            attributeList.add(data20);
            attributeList.add(data21);
            attributeList.add(data22);
            attributeList.add(data23);
            attributeList.add(data24);
            attributeList.add(data25);
            attributeList.add(data26);
            attributeList.add(data27);
            attributeList.add(data28);
            attributeList.add(data29);
            attributeList.add(data30);
            attributeList.add(data31);
            attributeList.add(data32);
            attributeList.add(data33);
            attributeList.add(data34);
            attributeList.add(data35);
            attributeList.add(data36);
            attributeList.add(data37);
            attributeList.add(data38);
            attributeList.add(data39);
            attributeList.add(data40);
            attributeList.add(data41);
            attributeList.add(data42);
            attributeList.add(data43);
            attributeList.add(data44);
            attributeList.add(data45);
            attributeList.add(data46);
            attributeList.add(data47);
            attributeList.add(data48);
            attributeList.add(data49);
            attributeList.add(data50);
            attributeList.add(data51);
            attributeList.add(data52);
            attributeList.add(data53);
            attributeList.add(data54);
            attributeList.add(data55);
            attributeList.add(data56);
            attributeList.add(data57);
            attributeList.add(data58);
            attributeList.add(data59);
            attributeList.add(data60);
            attributeList.add(data61);
            attributeList.add(data62);
            attributeList.add(data63);
            attributeList.add(data64);
            attributeList.add(data65);
            attributeList.add(data66);
            attributeList.add(data67);
            attributeList.add(data68);
            attributeList.add(data69);
            attributeList.add(data70);
            attributeList.add(data71);
            attributeList.add(data72);
            attributeList.add(data73);
            attributeList.add(data74);
            attributeList.add(data75);
            attributeList.add(data76);
            attributeList.add(data77);
            attributeList.add(data78);
            attributeList.add(data79);
            attributeList.add(data80);
            attributeList.add(data81);
            attributeList.add(data82);
            attributeList.add(data83);
            attributeList.add(data84);
            attributeList.add(data85);
            attributeList.add(data86);
            attributeList.add(data87);
            attributeList.add(data88);
            attributeList.add(data89);
            attributeList.add(data90);
            attributeList.add(data91);
            attributeList.add(data92);
            attributeList.add(data93);
            attributeList.add(data94);
            attributeList.add(data95);
            attributeList.add(data96);
            attributeList.add(data97);
            attributeList.add(data98);
            attributeList.add(data99);
            attributeList.add(data100);
            attributeList.add(data101);
            attributeList.add(data102);
            attributeList.add(data103);
            attributeList.add(data104);
            attributeList.add(data105);
            attributeList.add(data106);
            attributeList.add(data107);
            attributeList.add(data108);
            attributeList.add(data109);
            attributeList.add(data110);
            attributeList.add(data111);
            attributeList.add(data112);
            attributeList.add(data113);
            attributeList.add(data114);
            attributeList.add(data115);
            attributeList.add(data116);
            attributeList.add(data117);
            attributeList.add(data118);
            attributeList.add(data119);
            attributeList.add(data120);
            attributeList.add(data121);
            attributeList.add(data122);
            attributeList.add(data123);
            attributeList.add(data124);
            attributeList.add(data125);
            attributeList.add(data126);
            attributeList.add(data127);
            attributeList.add(data128);

            attributeList.add(new Attribute("@@class@@",classVal));

            // Create new dataset
            Instances data = new Instances("TestInstances",attributeList,0);

            // Create new instance
            inst_co = new DenseInstance(data.numAttributes());

            // Set instance's values for attributes
            inst_co.setValue(data1, dataArray[0]);
            inst_co.setValue(data2, dataArray[1]);
            inst_co.setValue(data3, dataArray[2]);
            inst_co.setValue(data4, dataArray[3]);
            inst_co.setValue(data5, dataArray[4]);
            inst_co.setValue(data6, dataArray[5]);
            inst_co.setValue(data7, dataArray[6]);
            inst_co.setValue(data8, dataArray[7]);
            inst_co.setValue(data9, dataArray[8]);
            inst_co.setValue(data10, dataArray[9]);
            inst_co.setValue(data11, dataArray[10]);
            inst_co.setValue(data12, dataArray[11]);
            inst_co.setValue(data13, dataArray[12]);
            inst_co.setValue(data14, dataArray[13]);
            inst_co.setValue(data15, dataArray[14]);
            inst_co.setValue(data16, dataArray[15]);
            inst_co.setValue(data17, dataArray[16]);
            inst_co.setValue(data18, dataArray[17]);
            inst_co.setValue(data19, dataArray[18]);
            inst_co.setValue(data20, dataArray[19]);
            inst_co.setValue(data21, dataArray[20]);
            inst_co.setValue(data22, dataArray[21]);
            inst_co.setValue(data23, dataArray[22]);
            inst_co.setValue(data24, dataArray[23]);
            inst_co.setValue(data25, dataArray[24]);
            inst_co.setValue(data26, dataArray[25]);
            inst_co.setValue(data27, dataArray[26]);
            inst_co.setValue(data28, dataArray[27]);
            inst_co.setValue(data29, dataArray[28]);
            inst_co.setValue(data30, dataArray[29]);
            inst_co.setValue(data31, dataArray[30]);
            inst_co.setValue(data32, dataArray[31]);
            inst_co.setValue(data33, dataArray[32]);
            inst_co.setValue(data34, dataArray[33]);
            inst_co.setValue(data35, dataArray[34]);
            inst_co.setValue(data36, dataArray[35]);
            inst_co.setValue(data37, dataArray[36]);
            inst_co.setValue(data38, dataArray[37]);
            inst_co.setValue(data39, dataArray[38]);
            inst_co.setValue(data40, dataArray[39]);
            inst_co.setValue(data41, dataArray[40]);
            inst_co.setValue(data42, dataArray[41]);
            inst_co.setValue(data43, dataArray[42]);
            inst_co.setValue(data44, dataArray[43]);
            inst_co.setValue(data45, dataArray[44]);
            inst_co.setValue(data46, dataArray[45]);
            inst_co.setValue(data47, dataArray[46]);
            inst_co.setValue(data48, dataArray[47]);
            inst_co.setValue(data49, dataArray[48]);
            inst_co.setValue(data50, dataArray[49]);
            inst_co.setValue(data51, dataArray[50]);
            inst_co.setValue(data52, dataArray[51]);
            inst_co.setValue(data53, dataArray[52]);
            inst_co.setValue(data54, dataArray[53]);
            inst_co.setValue(data55, dataArray[54]);
            inst_co.setValue(data56, dataArray[55]);
            inst_co.setValue(data57, dataArray[56]);
            inst_co.setValue(data58, dataArray[57]);
            inst_co.setValue(data59, dataArray[58]);
            inst_co.setValue(data60, dataArray[59]);
            inst_co.setValue(data61, dataArray[60]);
            inst_co.setValue(data62, dataArray[61]);
            inst_co.setValue(data63, dataArray[62]);
            inst_co.setValue(data64, dataArray[63]);
            inst_co.setValue(data65, dataArray[64]);
            inst_co.setValue(data66, dataArray[65]);
            inst_co.setValue(data67, dataArray[66]);
            inst_co.setValue(data68, dataArray[67]);
            inst_co.setValue(data69, dataArray[68]);
            inst_co.setValue(data70, dataArray[69]);
            inst_co.setValue(data71, dataArray[70]);
            inst_co.setValue(data72, dataArray[71]);
            inst_co.setValue(data73, dataArray[72]);
            inst_co.setValue(data74, dataArray[73]);
            inst_co.setValue(data75, dataArray[74]);
            inst_co.setValue(data76, dataArray[75]);
            inst_co.setValue(data77, dataArray[76]);
            inst_co.setValue(data78, dataArray[77]);
            inst_co.setValue(data79, dataArray[78]);
            inst_co.setValue(data80, dataArray[79]);
            inst_co.setValue(data81, dataArray[80]);
            inst_co.setValue(data82, dataArray[81]);
            inst_co.setValue(data83, dataArray[82]);
            inst_co.setValue(data84, dataArray[83]);
            inst_co.setValue(data85, dataArray[84]);
            inst_co.setValue(data86, dataArray[85]);
            inst_co.setValue(data87, dataArray[86]);
            inst_co.setValue(data88, dataArray[87]);
            inst_co.setValue(data89, dataArray[88]);
            inst_co.setValue(data90, dataArray[89]);
            inst_co.setValue(data91, dataArray[90]);
            inst_co.setValue(data92, dataArray[91]);
            inst_co.setValue(data93, dataArray[92]);
            inst_co.setValue(data94, dataArray[93]);
            inst_co.setValue(data95, dataArray[94]);
            inst_co.setValue(data96, dataArray[95]);
            inst_co.setValue(data97, dataArray[96]);
            inst_co.setValue(data98, dataArray[97]);
            inst_co.setValue(data99, dataArray[98]);
            inst_co.setValue(data100, dataArray[99]);
            inst_co.setValue(data101, dataArray[100]);
            inst_co.setValue(data102, dataArray[101]);
            inst_co.setValue(data103, dataArray[102]);
            inst_co.setValue(data104, dataArray[103]);
            inst_co.setValue(data105, dataArray[104]);
            inst_co.setValue(data106, dataArray[105]);
            inst_co.setValue(data107, dataArray[106]);
            inst_co.setValue(data108, dataArray[107]);
            inst_co.setValue(data109, dataArray[108]);
            inst_co.setValue(data110, dataArray[109]);
            inst_co.setValue(data111, dataArray[110]);
            inst_co.setValue(data112, dataArray[111]);
            inst_co.setValue(data113, dataArray[112]);
            inst_co.setValue(data114, dataArray[113]);
            inst_co.setValue(data115, dataArray[114]);
            inst_co.setValue(data116, dataArray[115]);
            inst_co.setValue(data117, dataArray[116]);
            inst_co.setValue(data118, dataArray[117]);
            inst_co.setValue(data119, dataArray[118]);
            inst_co.setValue(data120, dataArray[119]);
            inst_co.setValue(data121, dataArray[120]);
            inst_co.setValue(data122, dataArray[121]);
            inst_co.setValue(data123, dataArray[122]);
            inst_co.setValue(data124, dataArray[123]);
            inst_co.setValue(data125, dataArray[124]);
            inst_co.setValue(data126, dataArray[125]);
            inst_co.setValue(data127, dataArray[126]);
            inst_co.setValue(data128, dataArray[127]);


            // Add instance to dataset
            data.add(inst_co);
            data.setClassIndex(data.numAttributes() - 1);

            // Intialize and run classifier
            WekaWrapper clasifyData = new WekaWrapper();
            result = clasifyData.classifyInstance(data.firstInstance());

        } catch (Exception e) {

            e.printStackTrace();
        }

        Log.d("", "Classification result = " + result); // 0.0 - chodzenie, 1.0 - stanie

        return result;
    }

}
